meta-pytorch/torchft

- .github/workflows/lint.yaml
- .github/workflows/unittest.yaml
- torchft/process_group_test.py
This sets up lint and unit test CI builds.
> ci: lint + unittest

- .github/workflows/lint.yaml
- .github/workflows/unittest.yaml
setup-python doesn't work on Amazon Linux. This switches to use only Amazon linux runners and https://github.com/marketplace/actions/setup-python-amazon-linux
Security wise since we pin a version there should be no issue
> ci: switch to amazon runners

- torchft/manager.py
- torchft/process_group.py
- torchft/process_group_test.py
- train_ddp.py
This adds `get_future()` support to `BabyWork` which is required for using ProcessGroupBaby with the torchft ddp integration.
This uses a thread with an extra queue to handle future completions. 
Notably this is partial support:
* the future returned currently is a None future rather than propagating the tensors which works fine as these are inplace operations
* only one of wait/get_future can be called, if you try to call both it will throw an error
Fixes so it actually uses NCCL instead of Gloo and updated unit test to pass.
Fixes so we always apply the state_dict from the main thread in a safe spot to avoid version counter errors.
```
pytest
```
run train_ddp.py on two GPUs
> train_ddp, process_group: fixes so CUDA works e2e

- proto/torchft.proto
- src/lighthouse.rs
- src/manager.rs
This adds heartbeats to the lighthouse from the manager. These run every 100ms and are intended to allow the lighthouse to very quickly identify which workers are live vs not and to eliminate the join window.
Test plan:
```
cargo test
```
run lightouse+2 train_ddp replicas
> lighthouse: add heartbeats

- Cargo.toml
- src/lighthouse.rs
- templates/index.html
- templates/status.html
This adds a dashboard to the lighthouse server.
Test plan:
Start lighthouse and run two train_ddp workers
lint+test.sh
> lighthouse: add dashboard

- proto/torchft.proto
- src/lighthouse.rs
- src/manager.rs
- templates/index.html
- templates/status.html
This adds a kill button to the dashboard.
It also will highlight when heartbeats have stopped.
Test plan:
run lighthouse + 1 train_ddp worker
cargo fmt, cargo test
> lighthosue, manager: dashboard kill and heartbeat old ui

- .github/workflows/unittest.yaml
- torchft/process_group_test.py
CI Fixes:
* Centos 7 rust is too old so we need to use rustup to build with a newer version of rust.
* Our current GPU runner only has one GPU so we need to check # of gpus when running tests that require more
> ci: use stable rust and gate on number of gpus

- Cargo.toml
- proto/torchft.proto
- src/lighthouse.rs
- templates/index.html
- templates/status.html
Dashboard updates to show the current quorum status, the age and highlight recovering workers.
Test plan:
Run lighthouse + two train_ddp workers
> dashboard: show quorum status, age, old replicas

- proto/torchft.proto
- src/lighthouse.rs
- src/manager.rs
- templates/status.html
- torchft/manager.py
- train_ddp.py
We allow setting a manual replica_id so the workers aren't continuously being recreated.
World size now shows on dashboard for convenience.
Verified loss converges
Test plan:
Lighthouse + 2 train_ddp
> train, manager, dashboard: show world size on dashboard, manual replica_id, convergence tweaks

- torchft/checkpointing.py
This adds ipv6 support to the CheckpointServer.
Test plan:
run train_ddp.py on machine with only ipv6
CI
> [checkpointing] support ipv6

- torchft/process_group.py
- torchft/process_group_test.py
This adds basic support for APIs that require registration such as DeviceMesh and _functional_collectives.
This hasn't been tested with any downstream libraries that use DeviceMesh such as FSDPv2. It is intended to be compatible with https://github.com/pytorch/pytorch/blob/443472b1cabac7758e59af7d80c25f99f3ec0fbd/torch/distributed/fsdp/_init_utils.py#L162
Test plan:
```
pytest torchft/process_group_test.py
```
> process_group: added registration to support DeviceMesh and functional_collectives

- README.md
It is actually not as easy as I originally imagined. So it worths to add a section for future users.
> Update README.md to include Rust installation

- torchft/process_group.py
If we don't specify the devices, c10d will print out the warning when we create a new group.
pytest process_group_test.py
> Specifiy the devices when registering the backend to avoid warnings

- torchft/manager.py
- torchft/manager_test.py
This refactors the manager to expose the underlying APIs needed to implement allreduce_grad. This is a first step to writing a wrapper PG that can integrate in with FSDP transparently.
Test plan:
```
```
> manager: expand API to include errors, participant information and numeric test

- torchft/manager.py
- torchft/process_group.py
- torchft/process_group_test.py
This introduces the beginnings of a specialized error swallowing process group wrapper. This is intended to be the basis of writing a `ManagedProcessGroup` that can be transparently used with libraries like FSDPv2/DeviceMesh that directly consume a process group.
This currently only wraps `allreduce` and not the other methods.
Test plan:
```
pytest
```
> process_group: wrapper updates and ErrorSwallowingProcessGroup

- src/bin/lighthouse.rs
- src/lib.rs
- src/lighthouse.rs
- src/manager.rs
This adds a basic Manager E2E test that spins up a lighthouse server to test with.
This also refactor the code so it's possible to bind lighthouse and manager to port 0 and fetch the port afterwards. This makes writing tests easier as they instead grab the first ephemeral port rather than a well known port.
Test plan:
```
cargo fmt
cargo test
```
> manager: added E2E tests and support getting lighthouse and manager addresses

- src/lib.rs
- torchft/manager.py
- torchft/manager_integ_test.py
This adds a recovery test that ensures a worker can crash and come back up.
Test plan:
```
pytest
```
> manager_integ_tests: added recovery test

- torchft/futures.py
- torchft/futures_test.py
- torchft/manager.py
- torchft/manager_test.py
- torchft/process_group.py
- torchft/process_group_test.py
This reduces dependency on the unreliable PG timeouts. We can now set a higher level timeout on all operations at the Manager level without having to have the NCCL/Gloo timeouts configured.
Test plan:
```
pytest
```
> manager: add CPU timeouts on allreduce/future calls

- pyproject.toml
- torchft/ddp.py
- torchft/manager.py
- torchft/manager_integ_test.py
- torchft/manager_test.py
This adds a multi rank recovery integration test
It also refactors the logging in Manager to be a bit more understandable when multiple ranks/replica logs are combined
Test plan:
```
pytest
```
> manager_integ_tests: added multi rank recovery

- torchft/manager.py
- torchft/manager_test.py
- torchft/optim.py
- torchft/optim_test.py
This is a small change to Manager to:
1. make it clearer by renaming `step` to `start_step`
2. shutdown the background thread to prevent leaks
Test plan:
```
pytest
```
> manager: rename step to start_step + small shutdown fix

- src/manager.rs
- torchft/manager.py
- torchft/manager_test.py
- torchft/optim.py
- torchft/optim_test.py
This renames `start_step` to `start_quorum` as we can now call it multiple times. The manager step is now only changed during `should_commit`. We also now support getting a quorum without healing.
`allow_heal` must be the same on all workers (TBD -- this may be hacky hmm since we don't know what state the workers are in.
This is work towards #39
Test plan:
```
pytest torchft/manager_test.py torchft/manager_integ_test.py
```
> manager: support multiple calls to start_quorum and conditional healing

- docs/source/index.rst
- docs/source/local_sgd.rst
- torchft/ddp.py
- torchft/ddp_test.py
- torchft/local_sgd.py
- torchft/local_sgd_test.py
- torchft/manager.py
- torchft/manager_test.py
This implements an initial version of LocalSGD. #39
This has some limitations:
* workers can only join at the start of the sync_every period
* in async mode, the joining worker will discard the first ``sync_every`` steps as it's treated as a single Manager step
* if any errors/workers fail we will only detect it at the end of ``sync_every`` steps
* This uses a copy of the weights in memory in order to restore the model on commit failure to guarantee we always step exactly ``sync_every`` steps on each worker. This copy will be required for DiLoCo to compute the pseudo gradient.
* We don't do any bucketization for the allreduce operation
Test plan:
```
pyre
pytest
```
This will require more testing as I've only tested it with a mocked Manager and no e2e/integration tests
> local_sgd: initial version of fault tolerant LocalSGD

- CONTRIBUTING.md
- torchft/process_group_test.py
Fix https://github.com/pytorch-labs/torchft/issues/32. Add a helper method `_test_pg` that runs multiple collectives. 
Potential follow ups:
- Update `ErrorSwallowingProcessGroupWrapper` and `ManangedProcessGroup` to support the other collectives
- additional consolidation of the tests. Can parametrize them based off the process group class?
- validate output values (maybe not necessary since this validation is done at pytorch collective level and these PGs are all wrapping those)
- move tests to a separate test folder
> Add _test_pg helper

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/unittest.yaml
- CONTRIBUTING.md
- docs/requirements.txt
- pyproject.toml
- Upgrade GHA step versions
- Add urls to pyproject.toml so they appear on pypi
- Add docs build section to contributing.md
> [Chore] Couple of small chores

- .github/workflows/nightly.yaml
- .gitignore
- Cargo.toml
- build.rs
- scripts/patch_nightly_version.py
This adds an automatic nightly wheel build.
Test plan:
https://pypi.org/project/torchft-nightly/
https://github.com/pytorch-labs/torchft/actions/runs/12422512150/job/34684318974?pr=50
> .github: add nightly wheel builds

- build.rs
There's a warning about it. Goes away with this change
```
warning: use of deprecated method `tonic_build::Builder::compile`: renamed to `compile_protos()`
--> build.rs:10:10
|
10 |         .compile(&["proto/torchft.proto"], &["proto"])?;
|          ^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: `torchft` (build script) generated 1 warning
```
> chore: compile -> compile_protos

- torchft/local_sgd.py
- torchft/manager_integ_test.py
This adds an integration test for LocalSGD that tests one of the replicas crashing and recovering.
This runs for 8 steps with `sync_every=2` and 4 manager steps.
This mostly is refactoring the integration tests into a more flexible `Runner` class and adds a new `local_sgd_train_loop`. It does fix one bug in LocalSGD where we don't detach the gradient before running the all reduce.
cc @Jackmin801 
Test plan:
```
pytest torchft/manager_integ_test.py -k local_sgd -s -x
```
> manager_integ_tests: added LocalSGD integration test

- src/lib.rs
- src/manager.rs
- torchft/manager.py
- torchft/manager_integ_test.py
- torchft/manager_test.py
- torchft/torchft.pyi
This adds per request timeouts to all the ManagerClient methods. It also forwards the timeout from the manager to the lighthouse for quorum operations.
Test plan:
updated unit tests
```
pytest
cargo test
```
> manager: add per request timeouts

- torchft/manager.py
- torchft/process_group.py
- torchft/process_group_test.py
This does two things:
1) add PG init timeouts for ProcessGroupGloo and ProcessGroupBabyGloo/NCCL -- this does not add a timeout for ProcessGroupNCCL as it doesn't block on initialization so we can rely on our existing future timeouts
2) automatically assigns the manager port rather than requiring it to be manually set
Test plan:
```
pytest torchft/process_group_test.py
```
> process_group: add PG init timeouts + automatically assign manager port

- src/lib.rs
- src/manager.rs
- torchft/manager.py
- torchft/torchft.pyi
This fixes the announced address when the manager binds to port 0. Previously we were announcing an address with port 0 which caused a connection error when restoring from checkpoint.
Test plan:
```
torchft_lighthouse --min_replicas 2 --join_timeout_ms 1000
CUDA_VISIBLE_DEVICES=0 TORCHFT_LIGHTHOUSE=http://localhost:29510 torchrun --master_port 29502 --nnodes 1 --nproc_per_node 1 --max-restarts 10 train_ddp.py
CUDA_VISIBLE_DEVICES=1 TORCHFT_LIGHTHOUSE=http://localhost:29510 torchrun --master_port 29501 --nnodes 1 --nproc_per_node 1 --max-restarts 10 train_ddp.py
```
> [manager] fix address when binding to 0

- docs/requirements.txt
Summary:
Update jinja to address dependabot reported alerts.
1. Jinja has a sandbox breakout through malicious filename
2. Jinja has a sandbox breakout through indirect reference to format method.
Test Plan:
Test on github
> feat: fix security warnings in torchft

- proto/torchft.proto
- src/lib.rs
- src/lighthouse.rs
- src/manager.rs
- templates/status.html
- torchft/manager.py
- torchft/torchft.pyi
This removes previously added room support in #48
This didn't work out in practice as expected and will be instead replaced with "shrink only" quorum support which is a bit easier to reason about and doesn't require absurdly long timeouts.
Test plan:
```
pytest
cargo test
```
> lighthouse, manager: remove room support

- proto/torchft.proto
- src/lib.rs
- src/lighthouse.rs
- src/manager.rs
- torchft/lighthouse_test.py
- torchft/manager.py
- torchft/torchft.pyi
This modifies the quorum behavior with a few major changes:
1. the quorum won't complete unless at least half of the heartbeating replicas join the quorum (this is to avoid split brain conditions) except in fast quorum cases when we're growing the quorum
Rational: in scale up scenarios we could end up in split brain cases where min_replicas=2, but total replicas = 10 and we end up flip/flopping the quorum with effectively two separate jobs
2. the join_timeout now only applies if there's a heartbeating replica which hasn't joined the quorum 
Rational: since heartbeating starts when manager starts (often before model init), there's not much use in waiting out the full time since we probably won't have any workers join and we have at least min_replicas
(TODO: should we remove fast quorum as …
> lighthouse/quorum: avoid split brain and add shrink_only support

- README.md
- train_ddp.py
> Fix typo and use sampler in train_ddp.py

- Cargo.toml
- src/lib.rs
- src/lighthouse.rs
- src/manager.rs
- src/net.rs
- src/retry.rs
- src/timeout.rs
- torchft/checkpointing.py
- torchft/checkpointing_test.py
- torchft/manager.py
- torchft/process_group_test.py
- torchft/torchft.pyi
This overhauls the timeouts for all network operations to allow for long quorum timeouts in a safer way.
Notable changes:
* removes timeout from the Endpoint/Channel/Client in favor of using keep alives + server based timeouts
* adds timeouts to CheckpointServer
* requires timeouts to be passed for all Rust operations
* adds a new `quorum_timeout` field to Manager py so you can have a much longer quorum timeout
Test plan:
```
pytest
cargo test
```
> overhaul timeouts for Lighthouse, Manager, checkpoint server

- .pyre_configuration
- .torchxconfig
- CONTRIBUTING.md
- pyproject.toml
- src/lib.rs
- src/lighthouse.rs
- templates/status.html
- torchft/manager_integ_test.py
- torchft/torchx.py
- train_ddp.py
This adds a torchx component that can be used to run many replica tests locally. This is intended to make it easier to validate E2E behavior since it's now 2 commands to run an e2e job with `train_ddp.py`.
TorchX is a job launcher and the component we create will launch one role per replica group with torchelastic managing the workers within each group. Elastic uses a port range `29600 + replica_id`.
It also includes some small tweaks to logging, static types and the Lighthouse dashboard for monitoring.
Test plan:
```
torchft_lighthouse --min_replicas 2 --join_timeout_ms 10000 &
torchx run -- --replicas 20
```
Increasing the join timeout is required to avoid split brain issues when some replicas are recovering. 
From experimentation, join_timeout_ms must be longer than the recovery time …
> use torchx for manual many replica (20+) tests

- src/lib.rs
This fixes errors from Rust when calling the manager from multiple threads.
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/mreso/torchft/train_fsdp.py", line 176, in <module>
[rank1]:     main()
[rank1]:   File "/home/mreso/torchft/train_fsdp.py", line 169, in main
[rank1]:     optimizer.step()
[rank1]:   File "/home/mreso/torchft/torchft/optim.py", line 53, in step
[rank1]:     if self.manager.should_commit():
[rank1]:   File "/home/mreso/torchft/torchft/manager.py", line 556, in should_commit
[rank1]:     should_commit = self._client.should_commit(
[rank1]: RuntimeError: Already borrowed
```
We have the Manager receiver type set as `&mut self` when it really doesn't need to be. We instead do a lightweight clone of the client when making network calls.
See …
> lib: fix Already borrowed

- torchft/process_group.py
- torchft/process_group_test.py
This modified the configure behavior in ProcessGroupBaby so that we wait for the futher thread to be terminated before we create new ones. This fixed a race condition where futher queue might be closed while futher thread was still trying to get item from it.
Test plan:
Added test cases for reconfiguring ProcessGroupBaby and included assertions to make sure internal state is set as expected.
> process_group: wait for futher_thread join before creating new one

- proto/torchft.proto
- src/lib.rs
- src/manager.rs
- torchft/checkpointing.py
- torchft/checkpointing_test.py
- torchft/manager.py
- torchft/manager_integ_test.py
- torchft/manager_test.py
- torchft/torchft.pyi
This is a major refactoring of the live checkpointing code.
New behavior:
* Uses round robin recovery rather than all workers recovering from the primary (new logic in compute_quorum_result)
Key refactors:
* made a new generalized `CheckpointTransport` which `CheckpointServer` implements. This abstraction is designed to be symmetric for recovery strategies that require both sender and receiver to be aware of the communication. This will allow for recovering via ProcessGroups/NCCL which can be significantly faster.
* Made `ManagerClient.quorum` return a `QuorumResult` struct rather than a named tuple
* Renamed `checkpoint_address` to `checkpoint_metadata` as not all transports will be using an address
* Refactored recovery logic into `compute_quorum_result` method and added better unit …
> checkpointing: use CheckpointTransport abstraction

- torchft/process_group.py
- torchft/process_group_test.py
Without this we will start running operations before the process group has been reconfigured/initialized. This can result in crashes, timeouts and deadlocking
When using Manager `allreduce` this already is the behavior so we just need to make sure we match the behavior for ManagedProcessGroup.
This was observed in https://github.com/pytorch/torchtitan/pull/806
Test plan:
```
pytest
lintrunner -a
```
Testing w/ https://github.com/pytorch/torchtitan/pull/806
> process_group/ManagedProcessGroup: ensure quorum and PG is configured

- torchft/process_group.py
As titled, fixes docs build with the new version of PyTorch
Test plan:
```
cd docs && make html
```
> process_group: fix docs with torch==2.6.0

- torchft/device_mesh_test.py
- torchft/process_group.py
- torchft/process_group_test.py
There are missing gaps of ManagedDeviceMesh to be actually used in TorchTitan. This PR fixes the gpas:
1. ManagedDeviceMesh is now able to be torch.save()/torch.load().
2. ManagedDeviceMesh will lie if there are zero replicated group participants. Size 0 DeviceMesh will cause confusion for training loops.
3. Corretly returns coordinates.
> Fix ManagedDeviceMesh composability issues

- torchft/process_group.py
- torchft/process_group_test.py
This makes ProcessGroupBaby pass the PG test suite and fixes some glaring gaps in functionality.
* AllreduceOptions (and others) are now supported through a custom option wrapper
* implements allgather, broadcast
* BabyWork supports calling .wait() and .get_future() simultaneously
* BabyWork will clean up even if .wait isn't called
This should allow ProcessGroupBabyNCCL to be used with TorchTitan
Test plan:
```
pytest torchft/process_group_test.py
```
> ProcessGroupBaby: support full suite of PG tests

- torchft/checkpointing.py
- torchft/manager.py
- torchft/manager_test.py
This PR closes some state_dict gaps when integrating with TorchTitan:
1. User state_dict() and load_state_dict() functions can be initialized lazily.
2. Change weights_only to False for torch.load as we may have to load some non-tensor states.
> Change how TorchFT manages user_state_dict

- torchft/optim.py
- torchft/optim_test.py
OptimizerWrapper currently miss several attributes that are required for training integration. This PR adds the missing gap.
> Improve OptimizerWrapper composability

- torchft/local_sgd.py
- torchft/local_sgd_test.py
- torchft/manager_integ_test.py
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #76
```python
model = SimpleModel()
optimizer = optim.SGD(model.parameters())
manager = create_autospec(Manager)
with LocalSGD(manager, model, optimizer, sync_every=2):
for inp, label in dataloader:
loss = model(inp).mean()
loss.backward()
optimizer.step()
model = SimpleModel()
inner_optimizer = torch.optim.AdamW(
m.parameters(), lr=4e-4, weight_decay=0.1, betas=(0.9, 0.95)
)
outer_optimizer = torch.optim.SGD(
m.parameters(), lr=0.7, momentum=0.9, nesterov=True
)
manager = create_autospec(Manager)
with DiLoCo(manager, model, inner_optimizer, outer_optimizer, sync_every=2):
for inp, label in dataloader:
loss = model(inp).mean()
loss.backward()
inner_optimizer.step()
```
- Updated `LocalSGD` to be a context …
> Add DiLoCo

- torchft/process_group.py
- torchft/process_group_test.py
This overhauls how we handle ProcessGroupBabyNCCL cuda events and streams. It also enables the PG test suite for BabyNCCL similar to #89 which enabled it for BabyGloo.
Key changes:
* BabyNCCL now is stream aware and will allocate one CUDA stream per `stream_id` in the parent process. This avoids issues when multiple streams are using NCCL and avoids any unintentional synchronization by using a single stream in the child process.
* BabyNCCL uses a CUDA event to synchronize the start of the NCCL operation. Previously BabyNCCL would immediately start running the NCCL operation even if the launching stream hadn't completed yet.
* Added `_pg_tests` for BabyNCCL
* Unified the codepath and got rid of _BabyNCCLWork/WORK_CLASS
* Detect when the subprocess has crashed and error out early
* …
> ProcessGroupBabyNCCL: support multiple streams and use event on start

- README.md
- src/lighthouse.rs
- train_ddp.py
This updates timeouts for `train_ddp.py` so it recovers fast and some documentation to make it clearer what each option does.
Test plan:
```
torchft_lighthouse --min_replicas 2 --join_timeout_ms 10000
torchx run -- --replicas 10
```
+ killing workers via dashboard
> examples,docs: adjust ddp example timeout and docs

- torchft/manager.py
- torchft/manager_test.py
This exposes the `participating_rank()` field so users of Manager can figure out which replica rank they currently are.
This allows for things like only having the rank 0 replica group checkpoint for efficiency reasons.
Test plan:
```
```
> manager: expose participating_rank

- src/lighthouse.rs
Small change to use tokio [interval](https://doc.servo.org/tokio/time/index.html#:~:text=The%20difference%20between%20interval%20and%20sleep%20is%20that%20an%20interval%20measures%20the%20time%20since%20the%20last%20tick%2C%20which%20means%20that%20.tick().await%20may%20wait%20for%20a%20shorter%20time%20than%20the%20duration%20specified%20for%20the%20interval%20if%20some%20time%20has%20passed%20between%20calls%20to%20.tick().await) instead of sleep for quorum ticks:
before (some drift between tick times):
```
torchft::lighthouse: 2025-02-05T12:58:35.978-08:00 - INFO Next quorum status: New quorum not, only have 0 participants, need min_replicas 2 [0/0 participants healthy][2 heartbeating][shrink_only=false]
torchft::lighthouse: 2025-02-05T12:58:36.078-08:00 - INFO Next quorum status: New …
```
> update lighthouse quorum_ticks to use interval

- torchft/multiprocessing.py
- torchft/multiprocessing_test.py
- torchft/process_group.py
- torchft/process_group_test.py
This is a wrapper around mp.Queue that fails fast when the subprocess exits. This means if subprocess BabyNCCL crashes we will report the error quickly rather than waiting for the timeout to elapse.
Test plan:
```
pytest -o log_cli=1 torchft/process_group_test.py torchft/multiprocessing_test.py -s -v -x
```
> MonitoredQueue: fail fast when subprocess exits

- torchft/checkpointing/__init__.py
- torchft/checkpointing/http_transport.py
- torchft/checkpointing/http_transport_test.py
- torchft/checkpointing/transport.py
- torchft/fsdp_test.py
- torchft/manager.py
This restructures `torchft.checkpointing` to move `CheckpointServer` to it's own file and rename it `HTTPTransport` in preparation for the new `PGTransport`.
This new structure will make it easier to add in changes for PGTransport as well as parallel/streaming HTTP transfers.
It also has a small fix to `fsdp_test` due to tests running in a different order now.
Test plan:
```
pytest
```
> checkpointing: move to subfolder

- torchft/process_group.py
- torchft/process_group_test.py
Partially addresses https://github.com/pytorch/torchft/issues/97 by adding `reduce_scatter` into `torchft`.
Concretely, this consists of a few pieces: 
- Introducing `reduce_scatter` into the `ProcessGroup` following the signature [here](https://github.com/pytorch/pytorch/blob/11f69808c64a65c68a4452250ba7719dcff27c78/torch/csrc/distributed/c10d/PyProcessGroup.hpp#L203
- In `ProcessGroup*` we essentially follow the behavior of other collectives:
- In `ProcessGroupWrapper`, it depends on the parent implementation
- In `ProcessGroupDummy`, it writes from the first input into output
- In `ProcessGroupBaby`, it asserts inputs and moves underlying storage into shared memory 
- Add `ReduceScatterOptions` in `_PickleSafeOptions`
- Introduces `reduce_scatter` as an option in `_test_pg`, however …
> Adds `reduce_scatter` into `torchft`

- torchft/process_group.py
- torchft/process_group_test.py
Continuation of work for https://github.com/pytorch/torchft/issues/97.
This PR:
- Adds more collectives:
- allreduce_coalesced
- alltoall_base
- barrier
- reduce_scatter
- send/recv
- Extends `process_group_test.py` to accommodate the above collectives
Note - the `process_group_test` adds several new tests, increasing the test time from 16s to 22s. Not sure how avoidable this is - a prior version of this PR took 36s!
Notably `allgather_into_tensor_coalesced` and `reduce_scatter_tensor_coalesced` were not added in this PR.  
It was part of the plan, but started seeing an error such as:
```
E       AttributeError: 'torch._C._distributed_c10d.ProcessGroupNCCL' object has no attribute 'allgather_into_tensor_coalesced'
```
This was confusing, but surely enough this is true, if we do `dir(pg)` …
> Adds more collectives to ProcessGroups

- torchft/checkpointing/http_transport_test.py
- torchft/checkpointing/pg_transport.py
- torchft/checkpointing/pg_transport_test.py
- torchft/checkpointing/transport_test.py
- torchft/process_group.py
This adds a ProcessGroup based CheckpointTransport to allow for transferring a state_dict via the backend network.
This supports NCCL with cuda devices and Gloo on CPU devices. DTensor is supported but other tensor subclasses will likely error.
This is cleaned up code from #104 
Additional changes:
* `ProcessGroupBaby`: pass the `timeout` parameter to the subprocess so we can catch NCCL timeouts
* refactored http_transport_test
1. preprocess the state_dict using pytree to separate the tensors from python objects
2. serialize the tensor metadata and the non-python objects using pickle
3. send the metadata size via send/recv
4. send the pickled buffer via send/recv
5. send each tensor via send/recv
These sends will send to each of the receiving peers simultaneously.
Receiving is largely the …
> checkpointing/PGTransport: add NCCL/Gloo transport for checkpoints

- docs/source/coordination.rst
- docs/source/index.rst
- pyproject.toml
- src/lib.rs
- torchft/_torchft.pyi
- torchft/coordination.py
- torchft/coordination_test.py
- torchft/lighthouse_test.py
- torchft/local_sgd_integ_test.py
- torchft/manager.py
- torchft/manager_integ_test.py
- torchft/manager_test.py
This exposes LighthouseServer, ManagerServer and ManagerClient so power users can directly call them to implement custom fault tolerance strategies.
It also renames some modules (`_torchft` for Rust lib) and methods to indicate which ones are private and subject to change.
This _does not_ expose a quorum algorithm currently. The plan is to add a new "simple quorum" interface that allows for custom data to be passed between members instead of the data required by the Manager.
We may also want to expose a pluggable quorum algorithm that can be passed into LighthouseServer to customize that as well.
Test plan:
```
cd docs && make livehtml
pytest
cargo test
```
> coordination: expose new low level torchft coordination API

- torchft/process_group_test.py
See https://github.com/pytorch/torchft/issues/109 for more context, but there was a desire to:
1. Have collectives be tested on their own
2. Test true resiliency behaviors
- Removes `_test_multi_pg` and replaces it with individual `run_{collective}_test`s
- Makes each `run_{collective}_test` robust to different world sizes (i.e. 1, 2, or 3) to be more generalizable
- Introduces `MultiPgBaseTest`, a base test that spins up process groups and threadpool executors on setup (and destroys on teardown) so they can be re-used inbetween each test invocation. 
- `MultiPgBaseTest` introduces:
-  `_run_parallel`, a convenience function to run a collective test across its process groups, and
- `_run_with_resiliency`, a convenience function that runs a collective test, invokes failure modes and tests …
> Enhances `process_group_test` 

- torchft/process_group.py
- torchft/process_group_test.py
Closes out https://github.com/pytorch/torchft/issues/97
This PR introduces support for `allgather_into_tensor_coalesced` and `reduce_scatter_tensor_coalesced`, similar to other supported collectives. This is a follow up to https://github.com/pytorch/torchft/pull/108
As noted in https://github.com/pytorch/torchft/pull/108, `allgather_into_tensor_coalesced` and `reduce_scatter_tensor_coalesced` are supported in the base `ProcessGroup` but not within `ProcessGroupNCCL`. 
@d4l3k  pointed out we may be able to create a regular `CppProcessGroup` and register a backend, rather than return the backend which is what we were doing before, which seemed to work!
> Adds support for `allgather_into_tensor_coalesced` and `reduce_scatter_tensor_coalesced` 

- pyproject.toml
Seems like #84 renamed the module but it was not updated in the `pyproject.toml`.
Got `ModuleNotFoundError: No module named 'torchft.torchft'`
> Rename torchft to _torchft in project.scripts section

- torchft/checkpointing/pg_transport.py
- torchft/checkpointing/pg_transport_bench.py
- torchft/checkpointing/pg_transport_test.py
- torchft/checkpointing/transport_test.py
- torchft/multiprocessing.py
- torchft/process_group.py
This adds a new `state_dict` argument to `PGTransport` that when provided will give a state_dict to use for doing in-place tensor operations. This has been measured at ~3x faster.
Correctness:
```
pytest torchft/checkpointing/pg_transport_test.py
```
The improvements have been measured via `pg_transport_bench`.
For inplace operation we see it at ~3x faster (15s -> 4-5s) for 12GB with 3MB tensors size. The remaining overhead is primarily from torchft ProcessGroupBaby queue communication and not proportional to the size of the tensors. 
Reducing this overhead requires some careful consideration and will be addressed in a follow up PR.
```
python torchft/checkpointing/pg_transport_bench.py --device cuda
python torchft/checkpointing/pg_transport_bench.py --device cuda --inplace
```
``` …
```
> PGTransport: add inplace transport (3x faster)

- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
- torchft/local_sgd_test.py
- torchft/manager_integ_test.py
Changes:
- Remove backup parameters from local_sgd
- clean up tests
- Make DiLoCo not a subclass of local_sgd (there is some code repetition, but I think this is okay if we want to use these as an example for using our torchft APIs)
> Clean up local_sgd and diloco

- Cargo.toml
- src/lib.rs
- src/lighthouse.rs
- src/manager.rs
- torchft/manager.py
Couple of changes to logging:
- Use a different logging crate
- Allow log level to be set with `RUST_LOG` env
- Add `log_if_changed` to lighthouse.rs so it will only log if there is a message change. The quorum tick is pretty frequent by default
- Preprend replica_id to manager.rs logs by adding a new logging macro `info_with_replica`
Open to suggestion / changes.
Previous log example:
full paste: P1747150901
New log example:
full paste: P1747151799
> Improve log readability

- README.md
Let me know if you'd prefer to have the `$` prefix to indicate user. Personally its a little annoying to have to remove it whenever I copy paste the command
> [Docs] small readme fix

- torchft/local_sgd_integ_test.py
Update local sgd tests to train the model on GPU and uses `ProcessGroupBabyNCCL` for synchronization
> Add GPU tests for local sgd / diloco

- torchft/process_group.py
There's an issue with the recent future event work that sometimes causes `cudart` to crash.
This tracks the stream so the future completes in the same stream that it was launched in which seems to avoid the cudart crash.
Stack trace:
```
Fatal Python error: Segmentation fault
Current thread 0x00007f3752b5c640 (most recent call first):
File "/home/tristanr/.conda/envs/torchft-3.10/lib/python3.10/site-packages/torch/cuda/streams.py", line 196 in wait
File "/home/tristanr/torchft/torchft/process_group.py", line 1180 in _future_handler
File "/home/tristanr/.conda/envs/torchft-3.10/lib/python3.10/threading.py", line 953 in run
File "/home/tristanr/.conda/envs/torchft-3.10/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
File …
```
> ProcessGroupBaby: support streams in futures

- .github/workflows/unittest.yaml
This adds a new CI build that uses torch nightly to make sure we're compatible with trunk.
Nightly doesn't support old versions of glibc/CUDA driver so we needed to make a few upgrades to the runners.
This makes a few changes to CI for compatibility:
* update to linux_job_v2.yaml which uses a newer glibc
* use Python 3.12 since 3.10 has issues with the older glibc
* use CUDA 12.4 for the newer driver
* switch to g5.12xlarge (4 GPU A10G) which are compatible with newer CUDA version and can run all the multi GPU tests
Test plan:
CI
> run CI with torch nightly

- pyproject.toml
- pytest.ini
- torchft/futures.py
- torchft/process_group.py
- torchft/process_group_test.py
This disables normal ProcessGroupNCCL timeouts and instead uses `_TimeoutManager` to provide user space NCCL abort semantics using a background timer thread and a CUDA event to track completion.
Notable changes:
* Every time we wait on `ProcessGroupNCCL` collective we register an abort callback that fires if it doesn't complete in time.
* Long timeouts will result in many extra timeout entries that aren't cancelled since we don't proactively cleanup the timer events.
* This depends on NCCL aborting which is known to be buggy in `NCCL 2.25.1-1`
* We use `_opts_hook` and `_wrap_work` to ProcessGroupWrapper to provide wrappers around the base ProcessGroupNCCL to add in this logic.
* We always disable the timeout passed to base ProcessGroupNCCL to avoid watchdog/heartbeat from failing. We may …
> ProcessGroupNCCL: use _TimeoutManager to provide sane NCCL abort semantics

- .github/workflows/unittest.yaml
This fixes CI by installing the correct protobuf library. The latest version of conda `protobuf` doesn't install `libprotobuf` which is what we actually need.
Test plan:
CI
> ci: fix protobuf dep

- torchft/process_group.py
- torchft/process_group_test.py
This sets the timeout for TCPStore initialization which is used by `ProcessGroupNCCL`. Without this we can hit NCCL watchdog timeout which is set to 100s for torchtitan. The default TCPStore timeout is 5 minutes which is too long.
Test plan:
```
pytest torchft/process_group_test.py -v -s -x -k timeout
```
> process_group: set timeout for TCPStore client connect

- torchft/manager.py
This uses a separate stream for recovery so we don't have any ordering issues with the main workload when using `PGTransport`.
Test plan:
tested in torchtitan
CI
> manager: use separate stream for recovery

- torchft/futures.py
- torchft/futures_test.py
This updates the TimeoutManager to use a deletion queue so we delete the CUDA events on the main thread. If we delete these on the background thread we can end up deadlocking and not calling future timeout.
This is critical for NCCL abort as cudaEventDestroy can block in scenarios when a NCCL operation is stuck.
Test plan:
Tested in torchtitan
```
pytest torchft/futures_test.py
```
> TimeoutManager: delete cuda events on main thread

- torchft/manager.py
- torchft/manager_test.py
- torchft/process_group.py
- torchft/process_group_test.py
This adds a mechanism for propagating abort errors to Manager via `ProcessGroup.errored()`.
Without this change we don't wait for all operations to complete in `Manager.should_commit` and even if an abort occurs we don't detect it as they're running asynchronously on the GPU and NCCL abort causes it to return successfully.
This intentionally adds a synchronization point in `should_commit`.
This also includes a small fix in the resiliency tests to avoid stream dependencies between different worker threads.
Test plan:
```
pytest -o log_cli=1 torchft/process_group_test.py -v -s -x -k 'NormalNcclMultiPgTest'
```
> ProcessGroupNCCL,Manager: surface async abort errors correctly

- Cargo.toml
- proto/torchft.proto
- src/lib.rs
- src/lighthouse.rs
- src/manager.rs
- torchft/_torchft.pyi
- torchft/coordination.py
- torchft/coordination_test.py
- torchft/lighthouse_test.py
This is to address the issue here: https://github.com/pytorch/torchft/issues/140
generated doc:
run the following test:
pytest torchft/coordination_test.py
pytest torchft/lighthouse_test.py -k test_lighthouse_client_behavior
> Support generic quorum api on LighthouseClient

- torchft/local_sgd_integ_test.py
`ProcessGroupBabyNCCL` has an issue with allreduce race condition that I haven't figured out.  I tried running in processes instead of threads and it works, but I haven't figured out a good way to update the integration tests yet.
The values of the tensor after the allreduce is not the same or expected, e.g.
```
BEFORE average, replica 1:08cb3c4c-365e-4c8f-86d2-87000e78f2ad [model.0.bias tensor([-0.0004,  0.0006, -0.0008], device='cuda:4')]
BEFORE average, replica 0:812b70ca-ce59-43f1-b602-18515f23d808 [model.0.bias tensor([ 0.0003,  0.0002, -0.0008], device='cuda:0')]
AFTER average, replica 1:08cb3c4c-365e-4c8f-86d2-87000e78f2ad [model.0.bias tensor([ 6.1110e-05,  5.4164e-04, -1.2743e-03], device='cuda:4')]
AFTER average, replica 0:812b70ca-ce59-43f1-b602-18515f23d808 [model.0.bias …
```
> disable cuda tests in local_sgd_integ_test

- src/lib.rs
- torchft/_torchft.pyi
- torchft/lighthouse_test.py
Address the comment in https://github.com/pytorch/torchft/pull/150/files#r2015127529 to make the input params of quorum optional.
> Make params of quorum of lighthouse client optional

- torchft/device_mesh_test.py
- torchft/fsdp_test.py
- torchft/process_group.py
FSDP+TP requires `_mesh_resources.get_root_mesh` support. This adds root information to `_mesh_resources` for the ManagedDeviceMesh as well as a few other fixes (`__repr__` and `__hash__`).
https://github.com/pytorch/pytorch/blob/main/torch/distributed/fsdp/_fully_shard/_fsdp_param.py#L291
> ManagedDeviceMesh: support TP

- proto/torchft.proto
- src/lib.rs
- src/manager.rs
- torchft/_torchft.pyi
- torchft/manager.py
- torchft/manager_integ_test.py
- torchft/manager_test.py
This is a version of https://github.com/pytorch/torchft/pull/127 with a few fixes to support init_sync.
Fixes https://github.com/pytorch/torchft/issues/117
Test plan:
```
cargo test
pytest torchft/manager_integ_test.py
```
> manager: Add option to skip initial sync

- torchft/manager.py
- torchft/manager_test.py
Fixes https://github.com/pytorch/torchft/issues/151
> Add max retries to quorum to avoid live locks

- torchft/local_sgd.py
- torchft/local_sgd_test.py
Tested in torchtitan (https://github.com/pytorch/torchtitan/pull/1122) when the model is sharded with FSDP we need to convert the params to local tensors, update, then back to DTensors.
Ideally I would like to add a test in the integration tests but that would require us to set up the device_mesh / FSDP for a model
> Support DTensor params in local_sgd/diloco

- torchft/process_group.py
- torchft/process_group_test.py
- torchft/torchx.py
- train_ddp.py
This has some key fixes to improve ProcessGroupNCCL abort behavior when timing out.
This previously had a bug where weren't correctly scheduling the stream_timeout when calling `.get_future()` as called by `allreduce()` in the torchft Manager.
This also modifies `train_ddp.py` to allow for running multiple workers on the same GPU + make it more network heavy so we stress the comm layer and abort.
Test plan:
Added new unit tests to `process_group_test.py`.
```
pytest torchft/process_group_test.py -v -s -x -k test_nccl_timeouts
```
train_ddp + failure injection via `kill`
```
torchx run -- --replicas 16 --max_restarts=10
```
> ProcessGroupNCCL: abort on get_future timeout

- .github/workflows/lint.yaml
- .github/workflows/unittest.yaml
- README.md
- torchft/checkpointing/_serialization.py
- torchft/checkpointing/pg_transport.py
- torchft/optim.py
- torchft/process_group.py
- torchft/process_group_test.py
This updates the minimum version of torch to be 2.7.0. There's some important fixes in PyTorch 2.7 that avoid crashes and other slow behavior.
CI has been flaky recently in large part due to segfaults caused by bugs in 2.6.
Test plan:
CI
> ci: use torch 2.7 RC builds

- torchft/manager.py
- torchft/manager_test.py
This makes errors during configure and checkpoint transfer be bubbled up via report_error/errored so we can instead retry rather than crashing.
Test plan:
```
```
+ e2e tests
> manager: gracefully handle errors from configure+checkpoint

- src/lib.rs
small change so something like `RUST_LOG=WARN` also works as opposed to only `RUST_LOG=warn` working
> Have RUST_LOG be case-insensitive

- proto/torchft.proto
- src/lib.rs
- src/lighthouse.rs
- src/manager.rs
- torchft/_torchft.pyi
- torchft/manager.py
This adds a new field to Lighthouse quorum for `commit_failures`. When a commit failure occurs, a network error has occurred and we thus force a new quorum to ensure that all workers reconfigure.
This is required so #182 will gracefully recover after failure.
Test plan:
```
cargo test
pytest torchft/manager_integ_test.py
```
> lighthouse: add commit_failures support

- proto/torchft.proto
- src/lib.rs
- src/manager.rs
- torchft/_torchft.pyi
- torchft/data.py
- torchft/data_test.py
- torchft/manager.py
- torchft/manager_test.py
- train_ddp.py
Distinguishes between replica rank and group rank across the projects as per #181.
Kept the API the same for all except for the DistributedSampler. I found the terminology especially confusing there. And since it is not used in torchTitan I changed the API.
All tests have passed. However, I am getting the following linter error. It doesn't seem like a problem with my code. 
```sh
@warren# lintrunner -a
Warning: Could not find a lintrunner config at: '.lintrunner.private.toml'. Continuing without using configuration file.
>>> General linter failure:
Advice (pyre) command-failed
Failed due to JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
Successfully applied all patches.
(/srv/apps/danny/miniconda3/envs/warren/torchtitan) root@sz-k8s-master:/srv/apps/warren/fork/torchft# 
``` …
> Distinguishing between replica rank and group rank across the project (#181)

- torchft/checkpointing/transport_test.py
- torchft/manager.py
- torchft/manager_test.py
> Add traceback to manager reported error

- torchft/process_group.py
Fixing this here instead of the changes in https://github.com/pytorch/torchtitan/pull/1170
Tested this change in Torchtitan
> Fix ManagedProcessGroup when used with c10d APIs

- torchft/quantization.py
- torchft/quantization_test.py
Low precision gradient synchronization has emerged from research as a viable strategy to reduce peak bandwidth between ranks and speed up training without* loss in model quality. There has been a lot of research literature focusing on gradient compression during training (links to quantization with rescaling, [product quantization](https://www.microsoft.com/en-us/research/wp-content/uploads/2013/11/pami13opq.pdf), [quantization with error feedback](https://arxiv.org/pdf/2004.14180)) with quantization based on rescaling being appealing due to low compute and memory overhead (product quantization requires expensive nearest neighbor lookup in the code book, quantization with error feedback requires error accumulation equal in size to the gradients).
Specifically, we would like to leverage …
> Introduce FP8 row-based quantization

- torchft/collectives.py
- torchft/collectives_test.py
- torchft/quantization.py
- torchft/quantization_test.py
This change introduces several extensions to the quantized collectives:
- FP8 reduce-scatter
- float16 and bfloat16 base types for the input tensors
- SUM reduce operation support
> Introduce FP8 reduce-scatter along with SUM and more base types

- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
- torchft/local_sgd_test.py
- torchft/manager.py
- torchft/manager_test.py
The recovery logic for new nodes joining the quorum is different compared to regular diloco. Primarily because we need to make sure all nodes allreduce fragments in the same order otherwise we can deadlock. In diloco, there's only 1 fragment so there's nothin to order.
- Decouple scheduling and waiting for allreduce futures in `_StreamingDiLoCoFragment`
- Parallelize the allreduce's needed by `bucketize_and_allreduce`
- Move the decision making logic about scheduling and blocking for allreduce to `DiLoCo` instead of doing that independently in each fragment. So that we can the recovery logic in one place. The step counts also need to be centralized.  See comments in `DiLoCo::_step_post_hook`
- Retry `quorum` indefinitely
- Move `local_step` to `manager` -- added comments on why this is …
> Add recovery for streaming diloco

- README.md
- torchft/local_sgd.py
- torchft/manager.py
- torchft/manager_test.py
- torchft/process_group.py
- train_ddp.py
- train_diloco.py
- `should_commit` currently waits for all scheduled work but we need to only wait for work for a fragment
- otherwise, we need to wait for all fragments, which just makes it regular diloco
- removed cuda synchronize when we check errors on process group otherwise we also wait for all the work to finish on the process group
- **_instead we synchronize on the current stream but this might not be needed though because the current steam is doing training only -- @d4l3k? also baby pg doesn't override `errored()` method_**
- remove waiting on pending futures in the manager, the callers need to ensure now that they wait for the futures to complete
- had to change manager `allreduce` to support using custom streams and sprinkle event to this stream when future is ready
- this way the users of the …
> Group work for each commit

- torchft/collectives.py
- torchft/futures.py
- torchft/local_sgd.py
- torchft/manager.py
- train_diloco.py
Summary:
- set the same stream as the one used for work in future continuations so that random streams don't depend on pg stream (this can make these streams dependent on the allreduce stream)
- wait on the work sent to pg's immediately on the fragment streams (used for allreduce) to make them depend on the pg stream and so that they don't depend on any future work that's submitted to those streams
- copy grads before allreduce so that the inner optimization can use those and it doesn't create a dependency between the default stream and the pg stream
- add back support for quantized allreduce in manager
- change return types to be consistent with pg allreduce
- the returned future from quantization collectives hangs (likely because set_result is not called?) so changed it to return the …
> support async in nccl pg

- torchft/collectives.py
- torchft/futures.py
- torchft/local_sgd.py
- torchft/manager.py
- torchft/multiprocessing_dummy_context.py
- train_diloco.py
Summary:
- running multiple processes a few limitations
- we can't get gpu profiles from subprocesses
- the results can differ because of cuda using a different context that can't run concurrently, this can make it hard to debug if there's something wrong with the code or if it's an artefact of cuda context
- use multiprocessing.dummy to use threads instead of process
Test Plan:
using the patch with baby nccl, we can get overlapping communication and computation
we cannot get the overlap when using multiple processes, indicating it has something to do with cuda context
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/213).
* #212
* __->__ #213
* #211
> add debugability for baby pg

- .gitignore
- train_diloco.py
Summary:
- add tensorboard integration and separate the metrics by run id and replica id
- have an output folder per replica id
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/214).
* #212
* #217
* #216
* #215
* __->__ #214
> add tensorboard to training script

- torchft/local_sgd.py
- torchft/local_sgd_test.py
Summary:
- fix setting `_local_tensor` of a dtensor directly
- fix allreduce bucketized to not use `parameter.grad`
- simplify some code
Test Plan:
- added a test to validate the gradient are saved and set correctly
- the previous test in `local_sgd_test` fails because allreduce is not performed on `param.grad`
- updated the test to first set the grads, then load the grads to make sure they reflect the allreduce result
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/215).
* #212
* #217
* #216
* __->__ #215
> fix gradient allreduce

- README.md
This adds PyPI installation instructions to the README to install the nightly build. This means end users don't need to install rust or protoc.
> README: Add PyPI instruction

- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
- torchft/local_sgd_test.py
- torchft/manager_integ_test.py
Summary:
- update diloco tests to work with model fragments
- propogate arguments for training loop and optimizer wrapper through test runner
- added a test that validates streaming diloco works when node crashes and rejoins
- store the whole manager state dict for validation instead of only user's default state dict
- fixed a bug that made the local step go out of sync
Test Plan:
```
pytest -vs ./torchft/local_sgd_integ_test.py
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/222).
* #223
* __->__ #222
> add streaming diloco test - recovery

- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
Summary:
- merge local and global parameters of the model after synchronization
- add the "alpha" parameter to integration tests
Test Plan:
```
pytest -vs ./torchft/local_sgd_integ_test.py
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/212).
* #230
* __->__ #212
> enable merging parameters for diloco

- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
Summary:
- support passing in a different outer optimizer for each fragment
- currently accept both list of optimizers and a single optimizer for backward compatibility
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/230).
* __->__ #230
* #212
> support multiple outer optims for diloco

- torchft/manager.py
Summary:
while training, we need to set higher quorum timeouts to make sure all replicas can finish training
these parameters are only exposed through the manager but users may not be able to access the manager directly e.g. when using torchtitan
so make the timeouts configurable using env vars that take precedence over the parameters passed through manager
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/229).
* #228
* __->__ #229
> make timeouts configurable

- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
- torchft/local_sgd_test.py
- torchft/test/diloco_trainer.py
Summary:
- since we made a simplifying assumption that we will only ever have 1 inflight fragment, we can simplify some of the logic particularly getting rid of the local step in manager state
- we'll just use the manager's step to determine which fragment to sync
- this also allows us to easily support heterogenous hardware by tuning the sync_every setting that will make slower/faster machines to perform less/more local steps before they sync
- we can also perform quorum right before preparing a fragment sync - this easily ensures that all replicas will have the same max step and sync the same fragment
- fix some numeric issues
- the sign of the pseudogradient
- inplace lerp when mixing local and global parameters
---
Stack created with …
> simplify streaming diloco

- torchft/_test/diloco_trainer.py
- torchft/diloco_regression_test.py
- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
Summary:
- external integration e.g. torchtitan don't have access to global parameters, which is diloco's internal state so they don't handle loading it or saving it
- we need to do this though so that the gradient computations can be correct when a node recovers
- set the global parameters inside diloco itself
Test Plan:
- the regression tests pass
- ran streamig diloco on 25 nodes with 1 fragment, syncing every 10 steps, with 2 step sync delay injecting failure every 7.5 minutes
> handle original parameters in diloco

- train_diloco.py
Summary:
use http transport instead of pg transport -- pg transport fails to resolve address when running locally
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/244).
* #248
* #243
* #240
* #247
* #246
* #245
* __->__ #244
> use http transport

- pyproject.toml
Fixing old hang-overs from before this became a PyTorch org project
> Fix project urls to not point to PyTorch-labs

- torchft/collectives.py
- torchft/local_sgd.py
- torchft/manager.py
- train_diloco.py
Summary:
- call future.wait in callbacks to make sure the continuation executes after the future has completed
- set the stream correctly to execute callback scheduled by bucketized allreduce
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/246).
* #249
* #240
* #248
* #245
* #243
* #247
* __->__ #246
* #244
> fix stream dependencies in callbacks

- torchft/collectives.py
- torchft/collectives_test.py
- torchft/ddp.py
- torchft/ddp_test.py
- torchft/local_sgd.py
- torchft/local_sgd_test.py
- torchft/manager.py
- torchft/manager_integ_test.py
- torchft/manager_test.py
- torchft/process_group.py
- torchft/process_group_test.py
- torchft/work.py
- train_diloco.py
Summary:
returns the work object so we can be more flexible with the usage
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/247).
* #249
* #240
* #248
* #245
* #243
* __->__ #247
* #246
* #244
> return work from manager allreduce

- torchft/local_sgd.py
- torchft/local_sgd_integ_test.py
- torchft/manager.py
- torchft/manager_test.py
Summary:
- the checkpointing wasn't thread safe for http transport so use lock the model in the pre step hook and when we want to transfer the checkpoint
> make checkpointing thread safe

- torchft/_test/managed_work_test.py
- torchft/ddp.py
- torchft/ddp_test.py
- torchft/local_sgd.py
- torchft/manager.py
- torchft/manager_integ_test.py
- torchft/manager_test.py
Summary:
- improve abstraction and api contract offered by  managed work - users can change future return types, ensures users use correct cuda streams
- added a managed future that is lazily attaches callbacks - based on when users call wait on the work  or the future
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchft/pull/253).
* #249
* __->__ #253
> clean up managed work

- examples/monarch/README.md
- examples/monarch/train_distributed.py
README should provide all necessary context for the script. We plan to iterate from here to add the following:
1. Cleanup of allocator logic once it is upstreamed in Monarch
2. Support for hot spares / host-level supervision
3. We could consider adding TrainerActor and a fleshed out ReplicaActor (with host supervision) to the library once they are in a more complete state, so that they are easily accessible to users.
> Add monarch+torchft distributed training example

- torchft/manager.py
- torchft/process_group.py
- torchft/process_group_test.py
Summary:
managed pg allreduce should just call manager's allreduce
> fix managed pg allreduce

- .github/workflows/nightly.yaml
Allows us to manually kick off nightly wheel builds
https://docs.github.com/en/actions/how-tos/manage-workflow-runs/manually-run-a-workflow?tool=webui
> Add manual trigger to nightly workflow
